name: movie-recommendation-api
channels:
  - conda-forge
dependencies:
  # v1.0: Basic Pipeline
  - python=3.10
  - pandas
  - joblib
  - pathlib
  - jupyterlab
  - seaborn
  - scikit-learn
  - scikit-surprise

  # v2.0: Experiment Tracking
  - mlflow

  # v3.0: API Server
  - fastapi
  - uvicorn[standard]
  - pydantic

  # v4.0: Dashboard
  - streamlit
  - requests

  # v5.0: Test & Polish
  - pytest
  - ipykernel

  # Necessary
  - pip